---
resources:
- name: hello-world-git
  type: git
  source:
    uri: https://github.com/jchapman68/hello-world.git
    branch: master

jobs: 
- name: acceptance-test
  public: true
  plan:
  - get: hello-world-git
  - task: run-acceptance-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: { repository: starkandwayne/concourse }

      inputs:
        - name: hello-world-git
      
      #run:
      #  path: ls
      
      run:
        path: hello-world-git/acceptancetest.sh
      params:
        URL: https://josh.apps.devtest.onsclofo.uk
        GREETING: 'Hello Joe'