---
resources:
- name: hello-world-git
  type: git
  source:
    uri: https://github.com/jchapman68/hello-world.git
    branch: master

- name: cf-devtest
  type: cf
  source:
    api: ********
    username: *********
    password: **********
    organization: paas
    space: josh
    


jobs:
- name: unit-test
  public: true
  plan:
  - get: hello-world-git
    trigger: true
  - task: run-unit-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: 
          repository: golang
          tag: alpine

      inputs:
        - name: hello-world-git
           
      run:
        path: go
        args: [test]
        dir: hello-world-git

- name: deploy-app
  public: true
  plan:
  - get: hello-world-git
    passed: [unit-test]
    trigger: true
  - put: cf-devtest
    params:
      manifest: hello-world-git/manifest.yml
      path: hello-world-git

- name: acceptance-test
  public: true
  plan:
  - get: hello-world-git
    passed: [deploy-app]
    trigger: true
  - task: run-acceptance-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: { repository: starkandwayne/concourse }

      inputs:
        - name: hello-world-git
         
      run:
        path: hello-world-git/acceptancetest.sh
      params:
        URL: ***********
        GREETING: 'Hello Joe'