---
resources:
- name: hello-world-git
  type: git
  source:
    uri: https://github.com/jchapman68/hello-world.git
    branch: master

- name: cf-devtest
  type: cf
  source:
    api: https://api.system.devtest.onsclofo.uk
    username: ((username))
    password: ((password))
    organization: paas
    space: josh
    

jobs:
- name: unit-test
  public: true
  serial_groups: [josh-half-pipe]
  plan:
  - get: hello-world-git
    trigger: true
  - task: run-unit-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: 
          repository: golang
          tag: alpine

      inputs:
        - name: hello-world-git
           
      run:
        path: go
        args: [test]
        dir: hello-world-git

- name: deploy-app
  public: true
  serial_groups: [josh-half-pipe]
  plan:
  - get: hello-world-git
    passed: [unit-test]
    trigger: true

  - task: create-some-files
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: 
          repository: golang
          tag: latest
      inputs:
      - name: hello-world-git
      outputs:
      - name: artifact
      run:
        path: hello-world-git/create_binary.sh

  - put: cf-devtest
    params:
      manifest: hello-world-git/manifest.yml
      path: artifact
      environment_variables:
        GREETING: Hello Joe


- name: acceptance-test
  public: true
  serial_groups: [josh-half-pipe]
  plan:
  - get: hello-world-git
    passed: [deploy-app]
    trigger: true
  - task: run-acceptance-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: { repository: starkandwayne/concourse }

      inputs:
        - name: hello-world-git
         
      run:
        path: hello-world-git/acceptancetest.sh
      params:
        URL: josh.apps.devtest.onsclofo.uk
        GREETING: 'Hello Joe'